build:
  image: ruby:$$RUBY_VERSION
  environment:
    - RAILS_ENV=test
  commands:
    - bundle install --quiet --path build/bundle
    - bundle exec rake test

cache:
  mount:
    - build/bundle
    - .git

matrix:
  RUBY_VERSION:
    - 2.2.9
    - 2.3.6
    - 2.4.3
    - 2.5.0
