sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
before_install:
  - gem update --system
  - gem update bundler
deploy:
  provider: rubygems
  api_key:
    secure: lPSnu1gYnaf/vcb5cfITcld/AxIPZzocWUYl7Yvn0dAPi/9VHikRvka3RQ5fHe+fhsNABGYatXA06PmEwITHRWc5YhDXholRoSr/GiyLdqfzTdWa/kxIfFUkh+clnwTgkbv5lpMICkpfT9BugpJjPhyKG40Tbjtzxox82XxWnVnwj6lOscCrKiXaFOEe4SGLVdv3vEm7IgmRboalpbnTUH51adTGbeDKaIxkkuUxSYaCtrHrpicaHsPPsoMp+mfabmuQ49F45rnwH61a87N5iHe/S8K7Nqw6GDyGRx9yIY6gh7U0PPgQgm5AOgrj1GUVlt5Fh9HfUyQMXuxFsZbUNgKcZpe8w5pokKOm/g4IQfpb9MHPl2JzSxeCAh19v/tyZaJUC/+hBQcze6S3Lycjriy9y8/j9xU83JjAgC9KCoR5+YmzwudMguq8DCIbnVPdBlaIWsNrZVPIwavDbNhorPnhc7hi8ehP7M6GpiYwqNgCJxJPN2dZIKSnb/OjECnTiaAGZlKoF8G1b7lK8zP35Sd93cJh3z5TS4bYz02JrGsHXQDvY9Wf9m9VNGoVcIDjdwbJN5TzToOFGF2pkepSgyucekfpWikHNEgGvyB5lJZ+iM106FreoM70O6nLWiFt/qg1+wo8IfjO5lQQYyskRuzj7/Cf/PPmf+4ClV8MHEw=
  gem: sms_kit
  on:
    tags: true
    repo: jamii-Technologies/sms_kit
    rvm: 2.5.0
